#!/usr/bin/env bash
set -euo pipefail

export KMP_DUPLICATE_LIB_OK=${KMP_DUPLICATE_LIB_OK:-TRUE}
export PYTORCH_ENABLE_MPS_FALLBACK=${PYTORCH_ENABLE_MPS_FALLBACK:-1}

export RAMSEY_R=${RAMSEY_R:-5}
export RAMSEY_N_MAX=${RAMSEY_N_MAX:-43}
export RAMSEY_CURR_START_N=${RAMSEY_CURR_START_N:-8}
export RAMSEY_SAT_EDGE_GATE=${RAMSEY_SAT_EDGE_GATE:-100}
export RAMSEY_SAT_MS=${RAMSEY_SAT_MS:-5000}
export RAMSEY_SAT_CALLS=${RAMSEY_SAT_CALLS:-2}
export RAMSEY_RESULTS_DIR=${RAMSEY_RESULTS_DIR:-./results_repo_game}

export RAMSEY_LAMBDA_SHAPE=${RAMSEY_LAMBDA_SHAPE:-0.10}
export RAMSEY_MCTS_SIMS=${RAMSEY_MCTS_SIMS:-96}
export RAMSEY_ROOT_NOISE_FRAC=${RAMSEY_ROOT_NOISE_FRAC:-0.30}
export RAMSEY_WIDEN_C=${RAMSEY_WIDEN_C:-8}
export RAMSEY_WIDEN_ALPHA=${RAMSEY_WIDEN_ALPHA:-0.50}
export RAMSEY_SUPPORT_S=${RAMSEY_SUPPORT_S:-10}
export RAMSEY_NETWORK=${RAMSEY_NETWORK:-resnet}  # or gnn

python -u muzero.py misere_ramsey
